/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'description' : string,
  'createdTimestamp' : bigint,
  'videoUrl' : string,
}
export type VideoId = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  'getLikeCount' : ActorMethod<[VideoId], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[VideoId], Video>,
  'getVideoCatalog' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribed' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'postComment' : ActorMethod<[VideoId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribe' : ActorMethod<[], undefined>,
  'unlikeVideo' : ActorMethod<[VideoId], undefined>,
  'unsubscribe' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];