/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VideoId = IDL.Text;
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [Video], ['query']),
  'getVideoCatalog' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'postComment' : IDL.Func([VideoId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribe' : IDL.Func([], [], []),
  'unlikeVideo' : IDL.Func([VideoId], [], []),
  'unsubscribe' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VideoId = IDL.Text;
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [Video], ['query']),
    'getVideoCatalog' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'postComment' : IDL.Func([VideoId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribe' : IDL.Func([], [], []),
    'unlikeVideo' : IDL.Func([VideoId], [], []),
    'unsubscribe' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };